version: 2
project_name: cloudflare-ddns
before:
  hooks:
    - go mod download
    - go run ./internal/generate/completions --date={{ .CommitDate }}
    - go run ./internal/generate/manpages --version={{ .Version }} --date={{ .CommitDate }}
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X main.version={{ .Version }}
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
archives:
  - formats: tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - LICENSE
      - README.md
      - manpages/*
      - completions/*
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
  groups:
    - title: Features
      order: 0
      regexp: "(feat)"
    - title: Fixes
      order: 1
      regexp: "(fix|perf)"
    - title: Dependencies
      order: 999
      regexp: '\(deps\):'
    - title: Others
      order: 998
brews:
  - homepage: https://github.com/gabe565/cloudflare-ddns
    description: Sync a Cloudflare DNS record with your public IP address
    license: Apache2
    repository:
      owner: gabe565
      name: homebrew-tap
    directory: Formula
    install: |
      bin.install "cloudflare-ddns"
      man1.install "manpages/cloudflare-ddns.1.gz"
      bash_completion.install "completions/cloudflare-ddns.bash" => "cloudflare-ddns"
      zsh_completion.install "completions/cloudflare-ddns.zsh" => "_cloudflare-ddns"
      fish_completion.install "completions/cloudflare-ddns.fish"
nfpms:
  - id: packages
    vendor: Gabe Cook
    homepage: https://github.com/gabe565/cloudflare-ddns
    description: Sync a Cloudflare DNS record with your public IP address
    license: Apache2
    maintainer: Gabe Cook <gabe565@gmail.com>
    formats:
      - deb
      - rpm
    contents:
      - src: ./manpages/
        dst: /usr/share/man/man1
        file_info:
          mode: 0644
      - src: ./completions/cloudflare-ddns.bash
        dst: /usr/share/bash-completion/completions/cloudflare-ddns
        file_info:
          mode: 0644
      - src: ./completions/cloudflare-ddns.fish
        dst: /usr/share/fish/vendor_completions.d/cloudflare-ddns.fish
        file_info:
          mode: 0644
      - src: ./completions/cloudflare-ddns.zsh
        dst:  /usr/share/zsh/vendor-completions/_cloudflare-ddns
        file_info:
          mode: 0644
publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -sf -Fpackage=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/gabe565/
aurs:
  - name: cloudflare-ddns-bin
    homepage: https://github.com/gabe565/cloudflare-ddns
    description: Sync a Cloudflare DNS record with your public IP address
    maintainers:
      - Gabe Cook <gabe565@gmail.com>
    license: Apache2
    private_key: '{{ .Env.AUR_SSH_KEY }}'
    git_url: ssh://aur@aur.archlinux.org/cloudflare-ddns-bin.git
    skip_upload: auto
    package: |-
      # bin
      install -Dm755 "./cloudflare-ddns" "${pkgdir}/usr/bin/cloudflare-ddns"
      # license
      install -Dm644 "./LICENSE" "${pkgdir}/usr/share/licenses/cloudflare-ddns/LICENSE"
      # man pages
      install -Dm644 "./manpages/cloudflare-ddns.1.gz" "${pkgdir}/usr/share/man/man1/cloudflare-ddns.1.gz"
      # completions
      install -Dm644 "./completions/cloudflare-ddns.bash" "${pkgdir}/usr/share/bash-completion/completions/cloudflare-ddns"
      install -Dm644 "./completions/cloudflare-ddns.zsh" "${pkgdir}/usr/share/zsh/site-functions/_cloudflare-ddns"
      install -Dm644 "./completions/cloudflare-ddns.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/cloudflare-ddns.fish"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
dockers:
  - &dockers
    image_templates:
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-amd64
    use: buildx
    dockerfile: goreleaser.Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
  - <<: *dockers
    image_templates:
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-armv7
    goarch: arm
    goarm: 7
    build_flag_templates:
      - "--platform=linux/arm/v7"
  - <<: *dockers
    image_templates:
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-arm64v8
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - &docker_manifests
    name_template: ghcr.io/gabe565/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-armv7
      - ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - <<: *docker_manifests
    name_template: ghcr.io/gabe565/{{ .ProjectName }}:{{ .Version }}
  - <<: *docker_manifests
    name_template: ghcr.io/gabe565/{{ .ProjectName }}:{{ .Major }}
  - <<: *docker_manifests
    name_template: ghcr.io/gabe565/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}
